server.port=9090

spring.datasource.url=jdbc:mariadb://localhost:3306/todos
spring.datasource.username=naokko
spring.datasource.password=cinna123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect